### ISSUE TITLE
Octave Parallel: Win 64

### ISSUE THREAD

**Issue by mzarowka** [GPawi/LANDO#2]
Octave seems to be unable to install parallel package on Win 10 (64 bit).

After running

`pkg install -forge parallel`

it throws an error and wont build. Which subsequently seems to affect behavior of LANDO notebook and processing. Is it possible to ditch code parallelization if needed?

Octave ver. 7.1.0

**Comment by GPawi** [comment]
Hi Maurycy, 
Thanks for bringing this to my attention. 
Unfortunately, you cannot skip the 'parallel' package in the current version of LANDO. I might need to find a way to make it optional in a later version. 
However, I developed LANDO with Octave version 6.4.0 - the 'parallel' package is not yet fully supported by the current version of Octave. (Octave 7.1 release date: 2022-04-06; parallel package release date: 2021-03-16) 
Would it be possible for you to uninstall Octave and reinstall it with the version 6.4? You can find the file here: https://www.artfiles.org/gnu.org/octave/windows/ .... and it should be either this file [octave-6.4.0-w64-64.zip](https://www.artfiles.org/gnu.org/octave/windows/octave-6.4.0-w64-64.zip) or this one [octave-6.4.0-w64-installer.exe](https://www.artfiles.org/gnu.org/octave/windows/octave-6.4.0-w64-installer.exe) 
Let me know, if this helped!

Best regards,
Gregor

**Comment by mzarowka** [comment]
Hi Gregor,

You are right, as I'm not using Octave myself I just downloaded the most recent one. With Octave 6.4 "parallel" pckg is now working, however I had to resort to manual installation providing the urls to forge.

I seem to stumble on some more errors and I don't know whether I should open next issue, or just mail you?

Best,
Maurycy

**Comment by GPawi** [comment]
Hi Maurycy,

it's good to hear that at least with the other Octave version you were able to install the "parallel" package. 

I would say for open science purpose and in case someone else has the same issue, it would be great if you can open another issue. Also just as a side note: I am currently working on my dissertation, which is why, I only have a few hours to spend on LANDO fixes. But around August, I will have more time and then I will also focus on the online version of LANDO to make it more accessible for others. 

Best regards,
Gregor
